version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:6.0
    container_name: post_metadata_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: post_metadata_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - post_api_network

  # API Service
  api:
    build: .
    container_name: post_metadata_api
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/post_metadata_db?authSource=admin
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - post_api_network
    volumes:
      - ./logs:/app/logs

volumes:
  mongodb_data:
    driver: local

networks:
  post_api_network:
    driver: bridge 